### ISSUE TITLE
Math

### ISSUE THREAD

**Issue by Zellerpooh** [Zellerpooh/zellerpooh.github.io#29]
### 线性代数
- [ ] [网易云课堂公开课](https://www.icourse163.org/learn/SDU-55001?tid=1003135002#/learn/content)
- [ ] [微分几何与广义相对论教程（北京师范大学梁灿彬教授）](https://www.bilibili.com/video/av1157024/?from=search&seid=10126358752879864979)
- [ ] [概率论与数理统计（浙江大学）](https://www.bilibili.com/video/av20027947?from=search&seid=3322663834369426402)

**Comment by Zellerpooh** [comment]
<?xml version="1.0"?>
<opml version="2.0">
  <head>
    <ownerEmail>
      zellerpooh@gmail.com
    </ownerEmail>
  </head>
  <body>
    <outline text="Kotlin ">
      <outline text="kotlin-for-android-developers">
        <outline text="Kotlin中的null安全" />
        <outline text="Flow control和ranges">
          <outline text="if表达式" />
          <outline text="When表达式" />
          <outline text="For循环" _note="for（item in collection）{ print(item) }" />
          <outline text="while和do/while循环" />
          <outline text="Ranges" _note="Range表达式使用一个&lt;b&gt; .. &lt;/b&gt;操作符，它是被定义实现了一个&lt;b&gt;rangTo&lt;/b&gt;方法">
            <outline text="rangeTo" _note="for (i in 0..10)&#10;	print(i)" />
            <outline text="downTo" _note="for(i in 10 downTo 0)&#10;	print(i)" />
            <outline text="step " _note="定义一个从1到一个值的不同的空隙&#10;for( i in 1..4 step 2) println(i)" />
            <outline text="until " _note="创建一个open range(不包含最后一项)&#10;for( i in 0 until 4) println(i)&#10;&#10;(i in 0 until list.size)" />
          </outline>
        </outline>
        <outline text="泛型">
          <outline text="内部声明变体(declaration-site variance)">
            <outline text="协变(covariance)" _note="out" />
            <outline text="逆变(contravariance)" _note="in" />
            <outline text="let" _note="它接收一个函数（接收一个对象，返回函数结果）作为参数，作为参数的函数返回的结果作为整个函数的返回值&#10;inline fun &amp;lt;T, R&amp;gt; T.let(f: (T) -&amp;gt; R): R = f(this)" />
            <outline text="with" _note="接收一个对象和一个函数，这个函数会作为这个对象的扩展函数执行，这表示我们根据推断可在函数内使用this&#10;inline fun &amp;lt;T,R&amp;gt; with(receiver: T, f: T.() -&amp;gt; R) : R=receiver.f()&#10;" />
            <outline text="apply" _note="apply  可以避免创建builder的方式来使用，因为对象调用的函数可以根据自己的需要来初始化自己，然后 apply  函数会返回它同一个对象&#10;inline fun &amp;lt;T&amp;gt; T.apply(f: T.() -&amp;gt; Unit): T { f(); return this }&#10;" />
          </outline>
        </outline>
        <outline text="Questions">
          <outline text="Any " />
          <outline text="Range(..) 能作用于哪些集合类型，只能数组还是对其他集合也可以？" />
          <outline text="listOf()返回的是什么类型?  --&amp;gt;kotlin中的集合类型" />
          <outline text="如何创建一个单例" />
        </outline>
      </outline>
      <outline text="Confusion">
        <outline text="Idioms">
          <outline text="apply 为什么可以将返回Unit的表达式赋值给对象" />
          <outline text="with 是如何实现调用对象的方法的" />
          <outline text="reified 关键字在泛型使用中的作用" />
          <outline text="inline 关键字的作用" />
        </outline>
      </outline>
      <outline text="Getting Started">
        <outline text="Basic Syntax" />
        <outline text="Idioms">
          <outline text="apply (Builder-style usage of methods that return Unit) " _note="https://kotlinlang.org/docs/reference/idioms.html#builder-style-usage-of-methods-that-return-unit" />
          <outline text="Calling multiple methods on an object instance (with)" _note="https://kotlinlang.org/docs/reference/idioms.html#calling-multiple-methods-on-an-object-instance-with" />
          <outline text="Configuring properties of an object (apply)" _note="https://kotlinlang.org/docs/reference/idioms.html#configuring-properties-of-an-object-apply&#10;当对象的构造函数中不存在属性配置时，很有用" />
          <outline text="Java 7's try with resources" _note="https://kotlinlang.org/docs/reference/idioms.html#java-7s-try-with-resources" />
          <outline text="Convenient form for a generic function that requires the generic type information(方便需要泛型信息的泛型函数)" _note="https://kotlinlang.org/docs/reference/idioms.html#convenient-form-for-a-generic-function-that-requires-the-generic-type-information" />
          <outline text="Consuming a nullable Boolean (产生一个可能为空的布尔值)" _note="val b: Boolean? = ...&#10;if (b == true) {&#10;    ...&#10;} else {&#10;    // `b` is false or null&#10;}" />
          <outline text="Swapping two variables" _note="var a = 1&#10;var b = 2&#10;a = b.also { b = a }" />
          <outline text="TODO(): Marking code as incomplete" _note="Kotlin's standard library has a TODO() function that will always throw a NotImplementedError. Its return type is Nothing so it can be used regardless of expected type. There's also an overload that accepts a reason parameter:&#10;&#10;fun calcTaxes(): BigDecimal = TODO(&quot;Waiting for feedback from accounting&quot;)" />
        </outline>
        <outline text="Coding Conventins(编码约定)" _note="Applying the style guide&#10;https://kotlinlang.org/docs/reference/coding-conventions.html#applying-the-style-guide">
          <outline text="Source code organization">
            <outline text="Directory structure" _note="the recommended directory structure follows the package structure with the common root package omitted." />
            <outline text="Source file names" _note="只包含一个类，名字为类名&#10;包含多个类或者只是top-level declarations,Use the camel case with an uppercase first letter (for example, ProcessDeclarations.kt)&#10;" />
            <outline text="Source file organization" />
            <outline text="Class layout" _note="Property declarations and initializer blocks&#10;Secondary constructors&#10;Method declarations&#10;Companion object" />
            <outline text="Interface implementation layout" />
            <outline text="Overload layout" _note="方法重载一定要紧挨着" />
          </outline>
          <outline text="Naming rules" _note="packges 小写且不能使用下划线，必须用多个单词时，用小写开头的驼峰式&#10;classes 大写字母开头的驼峰式&#10;">
            <outline text="Funtion names" _note="Names of functions, properties and local variables start with a lower case letter and use the camel case and no underscores&#10;Exception: factory functions used to create instances of classes can have the same name as the class being created" />
            <outline text="Names for test methods" _note="spaces enclosed in backticks and underscores allowed" />
            <outline text="Property names" />
            <outline text="Names for backing properties" _note="If a class has two properties which are conceptually the same but one is part of a public API and another is an implementation detail, use an underscore as the prefix for the name of the private property:&#10;&#10;class C {&#10;    private val _elementList = mutableListOf&amp;lt;Element&amp;gt;()&#10;​&#10;    val elementList: List&amp;lt;Element&amp;gt;&#10;         get() = _elementList&#10;}" />
          </outline>
          <outline text="Formatting">
            <outline text="Indentation" _note=" 4spaces not tabs" />
            <outline text="Curly braces" _note="For curly braces, put the opening brace in the end of the line where the construct begins, and the closing brace on a separate line aligned horizontally with the opening construct." />
            <outline text="Hoorizontal whitespace" />
            <outline text="Colon" />
            <outline text="Class header formatting" _note="class Person(&#10;    id: Int,&#10;    name: String,&#10;    surname: String&#10;) : Human(id, name) { /*...*/ }" />
            <outline text="Modifiers" _note="order:&#10;public / protected / private / internal&#10;expect / actual&#10;final / open / abstract / sealed / const&#10;external&#10;override&#10;lateinit&#10;tailrec&#10;vararg&#10;suspend&#10;inner&#10;enum / annotation&#10;companion&#10;inline&#10;infix&#10;operator&#10;data" />
            <outline text="Annotation formatting" />
            <outline text="File annotations" _note="/** License, copyright and whatever */&#10;@file:JvmName(&quot;FooBar&quot;)&#10;&#10;package foo.bar" />
            <outline text="Function formatting" _note="fun longMethodName(&#10;    argument: ArgumentType = defaultValue,&#10;    argument2: AnotherArgumentType&#10;): ReturnType {&#10;    // body&#10;}" />
            <outline text="Expression body formatting" />
            <outline text="Property formatting" />
            <outline text="Formatting control flow statements" _note="if (condition) {&#10;    // body&#10;} else {&#10;    // else part&#10;}&#10;&#10;try {&#10;    // body&#10;} finally {&#10;    // cleanup&#10;}" />
            <outline text="Method call formatting" _note="drawSquare(&#10;    x = 10, y = 10,&#10;    width = 100, height = 100,&#10;    fill = true&#10;)" />
            <outline text="Chained call wrapping" _note="val anchor = owner&#10;    ?.firstChild!!&#10;    .siblings(forward = true)&#10;    .dropWhile { it is PsiComment || it is PsiWhiteSpace }" />
            <outline text="Lambda formatting" _note="list.filter { it &amp;gt; 10 }&#10;&#10;fun foo() {&#10;    ints.forEach lit@{&#10;        // ...&#10;    }&#10;}&#10;&#10;appendCommaSeparated(properties) { prop -&amp;gt;&#10;    val propertyValue = prop.get(obj)  // ...&#10;}&#10;&#10;foo {&#10;   context: Context,&#10;   environment: Env&#10;   -&amp;gt;&#10;   context.configureEnv(environment)&#10;}" />
            <outline text="" />
          </outline>
          <outline text="Documentation comments" _note="Use @param and @return only when a lengthy description is required which doesn't fit into the flow of the main text." />
          <outline text="Avoiding redundant constructs" _note="Do not leave unnecessary syntactic elements in code just &quot;for clarity&quot;">
            <outline text="Unit " _note="fun foo() { // &quot;: Unit&quot; is omitted here&#10;&#10;}" />
            <outline text="String templates" _note="println(&quot;$name has ${children.size} children&quot;)" />
          </outline>
          <outline text="Idiomatic use of language features">
            <outline text="Immutability" _note="Prefer using immutable data to mutable. Always declare local variables and properties as val rather than var if they are not modified after initialization.&#10;Always use immutable collection interfaces (Collection, List, Set, Map) to declare collections which are not mutated.&#10;&#10;// Bad: use of mutable collection type for value which will not be mutated&#10;fun validateValue(actualValue: String, allowedValues: HashSet&amp;lt;String&amp;gt;) { ... }&#10;&#10;// Good: immutable collection type used instead&#10;fun validateValue(actualValue: String, allowedValues: Set&amp;lt;String&amp;gt;) { ... }&#10;&#10;// Bad: arrayListOf() returns ArrayList&amp;lt;T&amp;gt;, which is a mutable collection type&#10;val allowedValues = arrayListOf(&quot;a&quot;, &quot;b&quot;, &quot;c&quot;)&#10;&#10;// Good: listOf() returns List&amp;lt;T&amp;gt;&#10;val allowedValues = listOf(&quot;a&quot;, &quot;b&quot;, &quot;c&quot;)" />
            <outline text="Default parameter values" _note="Prefer declaring functions with default parameter values to declaring overloaded functions." />
            <outline text="Type aliases" _note="If you have a functional type or a type with type parameters which is used multiple times in a codebase, prefer defining a type alias for it:&#10;&#10;typealias MouseClickHandler = (Any, MouseEvent) -&amp;gt; Unit&#10;typealias PersonIndex = Map&amp;lt;String, Person&amp;gt;" />
            <outline text="Lambda parameters" _note="In lambdas which are short and not nested, it's recommended to use the it convention instead of declaring the parameter explicitly. In nested lambdas with parameters, parameters should be always declared explicitly." />
            <outline text="Returns in a lambda" _note="Avoid using multiple labeled returns in a lambda." />
            <outline text="Named arguments" _note="Use the named argument syntax when a method takes multiple parameters of the same primitive type, or for parameters of Boolean type, unless the meaning of all parameters is absolutely clear from context.&#10;&#10;drawSquare(x = 10, y = 10, width = 100, height = 100, fill = true)&#10;" />
            <outline text="Using conditional statements" _note="return if (x) foo() else bar()&#10;&#10;return when(x) {&#10;    0 -&amp;gt; &quot;zero&quot;&#10;    else -&amp;gt; &quot;nonzero&quot;&#10;}&#10;&#10;The above is preferable to:&#10;&#10;if (x)&#10;    return foo()&#10;else&#10;    return bar()&#10;    &#10;when(x) {&#10;    0 -&amp;gt; return &quot;zero&quot;&#10;    else -&amp;gt; return &quot;nonzero&quot;&#10;}" />
            <outline text="Using nullable Boolean values in conditions" _note="If you need to use a nullable Boolean in a conditional statement, use if (value == true) or if (value == false) checks." />
            <outline text="Loops on ranges" />
            <outline text="Platform types" _note="fun apiCall(): String = MyJavaApi.getProperty(&quot;name&quot;)&#10;&#10;class Person {&#10;    val name: String = MyJavaApi.getProperty(&quot;name&quot;)&#10;}&#10;&#10;fun main() {&#10;    val name = MyJavaApi.getProperty(&quot;name&quot;)&#10;    println(name)&#10;}&#10;" />
            <outline text="Using scope functions apply/with/run/also/let" />
          </outline>
        </outline>
      </outline>
      <outline text="Basics">
        <outline text="Basic Types">
          <outline text="Numbers">
            <outline text="Built-in types" _note="Byte Short Int Long" />
            <outline text="Floating-point numbers" _note="Float Double" />
            <outline text="Literal constants (字面值常量)">
              <outline text="十进制 123" />
              <outline text="长整型 123L" />
              <outline text="16进制 0x0f" />
              <outline text="二进制 0b00001011" />
              <outline text="Doubles by default: 123.5, 123.5e10" />
              <outline text="Floast are tagged by f or F : 123.5f" />
            </outline>
            <outline text="Underscores in numeric literals (since 1.1) 数值常量中添加下划线 增加可读性" _note="val oneMillion = 1_000_000&#10;val creditCardNumber = 1234_5678_9012_3456L&#10;val socialSecurityNumber = 999_99_9999L&#10;val hexBytes = 0xFF_EC_DE_5E&#10;val bytes = 0b11010010_01101001_10010100_10010010" />
            <outline text="Representation" _note="On the Java platform, numbers are physically stored as JVM primitive types, unless we need a nullable number reference (e.g. Int?) or generics are involved. In the latter cases numbers are boxed." />
            <outline text="Explicit conversions (显示转换)" _note="As a consequence, smaller types are NOT implicitly converted to bigger types. This means that we cannot assign a value of type Byte to an Int variable without an explicit conversion&#10;&#10;val b: Byte = 1 // OK, literals are checked statically&#10;val i: Int = b // ERROR&#10;&#10;We can use explicit conversions to widen numbers&#10;&#10;val i: Int = b.toInt() // OK: explicitly widened&#10;print(i)&#10;" />
            <outline text="Operations">
              <outline text="Division of integers" _note="division between integers always returns an integer. Any fractional part is discarded&#10;To return a floating-point type, explicitly convert one of the arguments to a floating-point type." />
              <outline text="Bitwise operations" _note="shl(bits) – signed shift left&#10;shr(bits) – signed shift right&#10;ushr(bits) – unsigned shift right&#10;and(bits) – bitwise and&#10;or(bits) – bitwise or&#10;xor(bits) – bitwise xor&#10;inv() – bitwise inversion" />
            </outline>
            <outline text="Floating point numbers comparison" _note="Equality checks: a == b and a != b&#10;Comparison operators: a &amp;lt; b, a &amp;gt; b, a &amp;lt;= b, a &amp;gt;= b&#10;Range instantiation and range checks: a..b, x in a..b, x !in a..b" />
          </outline>
          <outline text="Characters" _note="Characters are represented by the type Char. They can not be treated directly as numbers&#10;转移字符:\t, \b, \n, \r, \', \&quot;, \\ and \$" />
          <outline text="Booleans" />
          <outline text="Arrays" _note="class Array&amp;lt;T&amp;gt; private constructor() {&#10;    val size: Int&#10;    operator fun get(index: Int): T&#10;    operator fun set(index: Int, value: T): Unit&#10;&#10;    operator fun iterator(): Iterator&amp;lt;T&amp;gt;&#10;    // ...&#10;}&#10;&#10;to create an array:&#10;arrayOf(1, 2, 3)  [1, 2, 3]  arrayOfNulls()&#10;指定Array大小并提供一个通过索引产生数组元素值的工厂函数:&#10;val asc = Array(5) { i -&amp;gt; (i * i).toString() }&#10;" />
          <outline text="Unsigned integers" />
          <outline text="Strings" _note="immutable&#10;">
            <outline text="String literals" _note="val text = &quot;&quot;&quot;&#10;    |Tell me and I forget.&#10;    |Teach me and I remember.&#10;    |Involve me and I learn.&#10;    |(Benjamin Franklin)&#10;    &quot;&quot;&quot;.trimMargin()&#10;&#10;trimMargin() 用于去除空格" />
            <outline text="String templates" _note="val i = 10&#10;println(&quot;i = $i&quot;) // prints &quot;i = 10&quot;&#10;&#10;val s = &quot;abc&quot;&#10;println(&quot;$s.length is ${s.length}&quot;) // prints &quot;abc.length is 3&quot;&#10;&#10;val price = &quot;&quot;&quot;&#10;${'$'}9.99&#10;&quot;&quot;&quot;" />
          </outline>
        </outline>
        <outline text="Packages and Imports" _note="import org.example.Message // Message is now accessible without qualification&#10;&#10;import org.example.* // everything in 'org.example' becomes accessible&#10;&#10;import org.example.Message // Message is accessible&#10;import org.test.Message as testMessage // testMessage stands for 'org.test.Message'&#10;" />
        <outline text="Control Flow">
          <outline text="If Expression" _note="In Kotlin, if is an expression, i.e. it returns a value. Therefore there is no ternary operator (condition ? then : else), because ordinary if works fine in this role.&#10;&#10;if branches can be blocks, and the last expression is the value of a block:" />
          <outline text="When Expression" _note="when (x) {&#10;    1 -&amp;gt; print(&quot;x == 1&quot;)&#10;    2 -&amp;gt; print(&quot;x == 2&quot;)&#10;    else -&amp;gt; { // Note the block&#10;        print(&quot;x is neither 1 nor 2&quot;)&#10;    }&#10;}" />
          <outline text="For Loops" _note="for (item in collection) print(item)&#10;&#10;for (i in array.indices) {&#10;    println(array[i])&#10;}" />
          <outline text="While Loops" _note="while (x &amp;gt; 0) {&#10;    x--&#10;}&#10;&#10;do {&#10;    val y = retrieveData()&#10;} while (y != null) // y is visible here!" />
          <outline text="Break and continue in loops" />
        </outline>
        <outline text="Returns and Jumps">
          <outline text="return" _note="By default returns from the nearest enclosing function or anonymous function." />
          <outline text="break" _note="Terminates the nearest enclosing loop." />
          <outline text="continue" _note="Proceeds to the next step of the nearest enclosing loop." />
          <outline text="Break and Continue Labels" _note="loop@ for (i in 1..100) {&#10;    for (j in 1..100) {&#10;        if (...) break@loop&#10;    }&#10;}" />
          <outline text="Return at Labels" />
        </outline>
      </outline>
      <outline text="类与继承">
        <outline text="类" />
        <outline text="构造函数">
          <outline text="主构造函数 " _note="class Person(name : String){&#10;}&#10;柱构造函数不包含任何代码，初始化代码放在初始化块中" />
          <outline text="次构造函数" _note="constructor关键字&#10;需要委托给主构造函数" />
        </outline>
        <outline text="创建类的实例" />
        <outline text="类成员" />
        <outline text="继承">
          <outline text="Any 所有类都有一个共同的超类" />
          <outline text="覆盖方法" _note="open &#10;override" />
          <outline text="覆盖属性" />
          <outline text="派生类初始化顺序" />
        </outline>
      </outline>
    </outline>
  </body>
</opml>

**Comment by Zellerpooh** [comment]
Kotlin 

- kotlin-for-android-developers
  - Kotlin中的null安全
  - Flow control和ranges
    - if表达式
    - When表达式
    - For循环
      "for（item in collection）{ print(item) }"
    - while和do/while循环
    - Ranges
      "Range表达式使用一个 .. 操作符，它是被定义实现了一个rangTo方法"
      - rangeTo
        "for (i in 0..10)
        	print(i)"
      - downTo
        "for(i in 10 downTo 0)
        	print(i)"
      - step 
        "定义一个从1到一个值的不同的空隙
        for( i in 1..4 step 2) println(i)"
      - until 
        "创建一个open range(不包含最后一项)
        for( i in 0 until 4) println(i)
        
        (i in 0 until list.size)"
  - 泛型
    - 内部声明变体(declaration-site variance)
      - 协变(covariance)
        "out"
      - 逆变(contravariance)
        "in"
      - let
        "它接收一个函数（接收一个对象，返回函数结果）作为参数，作为参数的函数返回的结果作为整个函数的返回值
        inline fun <T, R> T.let(f: (T) -> R): R = f(this)"
      - with
        "接收一个对象和一个函数，这个函数会作为这个对象的扩展函数执行，这表示我们根据推断可在函数内使用this
        inline fun <T,R> with(receiver: T, f: T.() -> R) : R=receiver.f()
        "
      - apply
        "apply  可以避免创建builder的方式来使用，因为对象调用的函数可以根据自己的需要来初始化自己，然后 apply  函数会返回它同一个对象
        inline fun <T> T.apply(f: T.() -> Unit): T { f(); return this }
        "
  - Questions
    - Any 
    - Range(..) 能作用于哪些集合类型，只能数组还是对其他集合也可以？
    - listOf()返回的是什么类型?  -->kotlin中的集合类型
    - 如何创建一个单例
- Confusion
  - Idioms
    - apply 为什么可以将返回Unit的表达式赋值给对象
    - with 是如何实现调用对象的方法的
    - reified 关键字在泛型使用中的作用
    - inline 关键字的作用
- Getting Started
  - Basic Syntax
  - Idioms
    - apply (Builder-style usage of methods that return Unit) 
      "https://kotlinlang.org/docs/reference/idioms.html#builder-style-usage-of-methods-that-return-unit"
    - Calling multiple methods on an object instance (with)
      "https://kotlinlang.org/docs/reference/idioms.html#calling-multiple-methods-on-an-object-instance-with"
    - Configuring properties of an object (apply)
      "https://kotlinlang.org/docs/reference/idioms.html#configuring-properties-of-an-object-apply
      当对象的构造函数中不存在属性配置时，很有用"
    - Java 7's try with resources
      "https://kotlinlang.org/docs/reference/idioms.html#java-7s-try-with-resources"
    - Convenient form for a generic function that requires the generic type information(方便需要泛型信息的泛型函数)
      "https://kotlinlang.org/docs/reference/idioms.html#convenient-form-for-a-generic-function-that-requires-the-generic-type-information"
    - Consuming a nullable Boolean (产生一个可能为空的布尔值)
      "val b: Boolean? = ...
      if (b == true) {
          ...
      } else {
          // `b` is false or null
      }"
    - Swapping two variables
      "var a = 1
      var b = 2
      a = b.also { b = a }"
    - TODO(): Marking code as incomplete
      "Kotlin's standard library has a TODO() function that will always throw a NotImplementedError. Its return type is Nothing so it can be used regardless of expected type. There's also an overload that accepts a reason parameter:
      
      fun calcTaxes(): BigDecimal = TODO("Waiting for feedback from accounting")"
  - Coding Conventins(编码约定)
    "Applying the style guide
    https://kotlinlang.org/docs/reference/coding-conventions.html#applying-the-style-guide"
    - Source code organization
      - Directory structure
        "the recommended directory structure follows the package structure with the common root package omitted."
      - Source file names
        "只包含一个类，名字为类名
        包含多个类或者只是top-level declarations,Use the camel case with an uppercase first letter (for example, ProcessDeclarations.kt)
        "
      - Source file organization
      - Class layout
        "Property declarations and initializer blocks
        Secondary constructors
        Method declarations
        Companion object"
      - Interface implementation layout
      - Overload layout
        "方法重载一定要紧挨着"
    - Naming rules
      "packges 小写且不能使用下划线，必须用多个单词时，用小写开头的驼峰式
      classes 大写字母开头的驼峰式
      "
      - Funtion names
        "Names of functions, properties and local variables start with a lower case letter and use the camel case and no underscores
        Exception: factory functions used to create instances of classes can have the same name as the class being created"
      - Names for test methods
        "spaces enclosed in backticks and underscores allowed"
      - Property names
      - Names for backing properties
        "If a class has two properties which are conceptually the same but one is part of a public API and another is an implementation detail, use an underscore as the prefix for the name of the private property:
        
        class C {
            private val _elementList = mutableListOf<Element>()
        ​
            val elementList: List<Element>
                 get() = _elementList
        }"
    - Formatting
      - Indentation
        " 4spaces not tabs"
      - Curly braces
        "For curly braces, put the opening brace in the end of the line where the construct begins, and the closing brace on a separate line aligned horizontally with the opening construct."
      - Hoorizontal whitespace
      - Colon
      - Class header formatting
        "class Person(
            id: Int,
            name: String,
            surname: String
        ) : Human(id, name) { /*...*/ }"
      - Modifiers
        "order:
        public / protected / private / internal
        expect / actual
        final / open / abstract / sealed / const
        external
        override
        lateinit
        tailrec
        vararg
        suspend
        inner
        enum / annotation
        companion
        inline
        infix
        operator
        data"
      - Annotation formatting
      - File annotations
        "/** License, copyright and whatever */
        @file:JvmName("FooBar")
        
        package foo.bar"
      - Function formatting
        "fun longMethodName(
            argument: ArgumentType = defaultValue,
            argument2: AnotherArgumentType
        ): ReturnType {
            // body
        }"
      - Expression body formatting
      - Property formatting
      - Formatting control flow statements
        "if (condition) {
            // body
        } else {
            // else part
        }
        
        try {
            // body
        } finally {
            // cleanup
        }"
      - Method call formatting
        "drawSquare(
            x = 10, y = 10,
            width = 100, height = 100,
            fill = true
        )"
      - Chained call wrapping
        "val anchor = owner
            ?.firstChild!!
            .siblings(forward = true)
            .dropWhile { it is PsiComment || it is PsiWhiteSpace }"
      - Lambda formatting
        "list.filter { it > 10 }
        
        fun foo() {
            ints.forEach lit@{
                // ...
            }
        }
        
        appendCommaSeparated(properties) { prop ->
            val propertyValue = prop.get(obj)  // ...
        }
        
        foo {
           context: Context,
           environment: Env
           ->
           context.configureEnv(environment)
        }"
      - 
    - Documentation comments
      "Use @param and @return only when a lengthy description is required which doesn't fit into the flow of the main text."
    - Avoiding redundant constructs
      "Do not leave unnecessary syntactic elements in code just "for clarity""
      - Unit 
        "fun foo() { // ": Unit" is omitted here
        
        }"
      - String templates
        "println("$name has ${children.size} children")"
    - Idiomatic use of language features
      - Immutability
        "Prefer using immutable data to mutable. Always declare local variables and properties as val rather than var if they are not modified after initialization.
        Always use immutable collection interfaces (Collection, List, Set, Map) to declare collections which are not mutated.
        
        // Bad: use of mutable collection type for value which will not be mutated
        fun validateValue(actualValue: String, allowedValues: HashSet<String>) { ... }
        
        // Good: immutable collection type used instead
        fun validateValue(actualValue: String, allowedValues: Set<String>) { ... }
        
        // Bad: arrayListOf() returns ArrayList<T>, which is a mutable collection type
        val allowedValues = arrayListOf("a", "b", "c")
        
        // Good: listOf() returns List<T>
        val allowedValues = listOf("a", "b", "c")"
      - Default parameter values
        "Prefer declaring functions with default parameter values to declaring overloaded functions."
      - Type aliases
        "If you have a functional type or a type with type parameters which is used multiple times in a codebase, prefer defining a type alias for it:
        
        typealias MouseClickHandler = (Any, MouseEvent) -> Unit
        typealias PersonIndex = Map<String, Person>"
      - Lambda parameters
        "In lambdas which are short and not nested, it's recommended to use the it convention instead of declaring the parameter explicitly. In nested lambdas with parameters, parameters should be always declared explicitly."
      - Returns in a lambda
        "Avoid using multiple labeled returns in a lambda."
      - Named arguments
        "Use the named argument syntax when a method takes multiple parameters of the same primitive type, or for parameters of Boolean type, unless the meaning of all parameters is absolutely clear from context.
        
        drawSquare(x = 10, y = 10, width = 100, height = 100, fill = true)
        "
      - Using conditional statements
        "return if (x) foo() else bar()
        
        return when(x) {
            0 -> "zero"
            else -> "nonzero"
        }
        
        The above is preferable to:
        
        if (x)
            return foo()
        else
            return bar()
            
        when(x) {
            0 -> return "zero"
            else -> return "nonzero"
        }"
      - Using nullable Boolean values in conditions
        "If you need to use a nullable Boolean in a conditional statement, use if (value == true) or if (value == false) checks."
      - Loops on ranges
      - Platform types
        "fun apiCall(): String = MyJavaApi.getProperty("name")
        
        class Person {
            val name: String = MyJavaApi.getProperty("name")
        }
        
        fun main() {
            val name = MyJavaApi.getProperty("name")
            println(name)
        }
        "
      - Using scope functions apply/with/run/also/let
- Basics
  - Basic Types
    - Numbers
      - Built-in types
        "Byte Short Int Long"
      - Floating-point numbers
        "Float Double"
      - Literal constants (字面值常量)
        - 十进制 123
        - 长整型 123L
        - 16进制 0x0f
        - 二进制 0b00001011
        - Doubles by default: 123.5, 123.5e10
        - Floast are tagged by f or F : 123.5f
      - Underscores in numeric literals (since 1.1) 数值常量中添加下划线 增加可读性
        "val oneMillion = 1_000_000
        val creditCardNumber = 1234_5678_9012_3456L
        val socialSecurityNumber = 999_99_9999L
        val hexBytes = 0xFF_EC_DE_5E
        val bytes = 0b11010010_01101001_10010100_10010010"
      - Representation
        "On the Java platform, numbers are physically stored as JVM primitive types, unless we need a nullable number reference (e.g. Int?) or generics are involved. In the latter cases numbers are boxed."
      - Explicit conversions (显示转换)
        "As a consequence, smaller types are NOT implicitly converted to bigger types. This means that we cannot assign a value of type Byte to an Int variable without an explicit conversion
        
        val b: Byte = 1 // OK, literals are checked statically
        val i: Int = b // ERROR
        
        We can use explicit conversions to widen numbers
        
        val i: Int = b.toInt() // OK: explicitly widened
        print(i)
        "
      - Operations
        - Division of integers
          "division between integers always returns an integer. Any fractional part is discarded
          To return a floating-point type, explicitly convert one of the arguments to a floating-point type."
        - Bitwise operations
          "shl(bits) – signed shift left
          shr(bits) – signed shift right
          ushr(bits) – unsigned shift right
          and(bits) – bitwise and
          or(bits) – bitwise or
          xor(bits) – bitwise xor
          inv() – bitwise inversion"
      - Floating point numbers comparison
        "Equality checks: a == b and a != b
        Comparison operators: a < b, a > b, a <= b, a >= b
        Range instantiation and range checks: a..b, x in a..b, x !in a..b"
    - Characters
      "Characters are represented by the type Char. They can not be treated directly as numbers
      转移字符:\t, \b, \n, \r, \', \", \\ and \$"
    - Booleans
    - Arrays
      "class Array<T> private constructor() {
          val size: Int
          operator fun get(index: Int): T
          operator fun set(index: Int, value: T): Unit
      
          operator fun iterator(): Iterator<T>
          // ...
      }
      
      to create an array:
      arrayOf(1, 2, 3)  [1, 2, 3]  arrayOfNulls()
      指定Array大小并提供一个通过索引产生数组元素值的工厂函数:
      val asc = Array(5) { i -> (i * i).toString() }
      "
    - Unsigned integers
    - Strings
      "immutable
      "
      - String literals
        "val text = """
            |Tell me and I forget.
            |Teach me and I remember.
            |Involve me and I learn.
            |(Benjamin Franklin)
            """.trimMargin()
        
        trimMargin() 用于去除空格"
      - String templates
        "val i = 10
        println("i = $i") // prints "i = 10"
        
        val s = "abc"
        println("$s.length is ${s.length}") // prints "abc.length is 3"
        
        val price = """
        ${'$'}9.99
        """"
  - Packages and Imports
    "import org.example.Message // Message is now accessible without qualification
    
    import org.example.* // everything in 'org.example' becomes accessible
    
    import org.example.Message // Message is accessible
    import org.test.Message as testMessage // testMessage stands for 'org.test.Message'
    "
  - Control Flow
    - If Expression
      "In Kotlin, if is an expression, i.e. it returns a value. Therefore there is no ternary operator (condition ? then : else), because ordinary if works fine in this role.
      
      if branches can be blocks, and the last expression is the value of a block:"
    - When Expression
      "when (x) {
          1 -> print("x == 1")
          2 -> print("x == 2")
          else -> { // Note the block
              print("x is neither 1 nor 2")
          }
      }"
    - For Loops
      "for (item in collection) print(item)
      
      for (i in array.indices) {
          println(array[i])
      }"
    - While Loops
      "while (x > 0) {
          x--
      }
      
      do {
          val y = retrieveData()
      } while (y != null) // y is visible here!"
    - Break and continue in loops
  - Returns and Jumps
    - return
      "By default returns from the nearest enclosing function or anonymous function."
    - break
      "Terminates the nearest enclosing loop."
    - continue
      "Proceeds to the next step of the nearest enclosing loop."
    - Break and Continue Labels
      "loop@ for (i in 1..100) {
          for (j in 1..100) {
              if (...) break@loop
          }
      }"
    - Return at Labels
- 类与继承
  - 类
  - 构造函数
    - 主构造函数 
      "class Person(name : String){
      }
      柱构造函数不包含任何代码，初始化代码放在初始化块中"
    - 次构造函数
      "constructor关键字
      需要委托给主构造函数"
  - 创建类的实例
  - 类成员
  - 继承
    - Any 所有类都有一个共同的超类
    - 覆盖方法
      "open 
      override"
    - 覆盖属性
    - 派生类初始化顺序
